wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.5
batch_size:
  desc: null
  value: 20
conv1_channels:
  desc: null
  value: 5
conv2_channels:
  desc: null
  value: 16
epochs:
  desc: null
  value: 10
hidden_nodes:
  desc: null
  value: 120
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
